### ISSUE TITLE
Error: Could not get code signature for running application (Catalina)

### ISSUE THREAD

**Issue by dserodio** [salomvary/soundcleod#204]
I just updated macOS to Catalina (10.15.4) and SoundCleod 1.4.0 would freeze when I launched it, so I tried SoundCleod 1.4.1-pre.0 before filing a bug report.

Now SoundCleod (1.4.1-pre.0) works, but throws the following error every time I launch it:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Could not get code signature for running application
    at startAutoUpdater (/Applications/SoundCleod.app/Contents/Resources/app.asar/auto-updater.js:26:15)
    at checkAutoUpdater (/Applications/SoundCleod.app/Contents/Resources/app.asar/auto-updater.js:8:26)
    at fs.access (/Applications/SoundCleod.app/Contents/Resources/app.asar/auto-updater.js:18:7)
    at FSReqWrap.oncomplete (fs.js:169:20)
```

**Comment by salomvary** [comment]
Hey, thanks for writing in! I am working on some updates including fixing SoundCleod on Catalina. Expect a new version in the next couple of weeks!

**Comment by salomvary** [comment]
New version is out, should fix all Catalina issues.
